Improved `DenseLQDynamicModel` construction to require less memory and build faster
MadNLP/DynamicNLPModels.jl pull request #31
Opened 2022-07-06 17:03 UTC by dlcole3

Reformulated source code to build the Hessian and Jacobian a block at a time for the dense model. Previously, all block matrices were built, stored, and then multiplied together, but this was very inefficient as many of the multiplications were redundant. Instead, each block within the block matrices were multiplied together only when needed within for loops. 

This PR includes:
- redefining `DenseLQDynamicBlocks` to only save the `A` block and the `B` block. The latter block only contains the first column of the actual block `B` matrix, and it does not contain the first rows of zeros. This also removed any sparse matrices, which were inefficient within `LinearAlgebra.mul!`
- redefining `_build_block_matrices` to match `DenseLQDynamicBlocks`.
- redefining `_build_H_blocks` 
- redefining `_build_G_blocks`. 
- defining a new function, `_build_dense_J1` to form the Jacobian from the `G` blocks
- updating `build_dense_lq_dynamic_model` to be consistent with these changes
- updating `get_s` and `get_u` for working with the new block `B` matrix

This PR does not include updating the sparse formulation (which is also somewhat inefficient) or redefining the internal functions to be non-allocating. These changes are still needed but will be met with other PRs.

2022-07-06 19:54 UTC, sshin23 approved these changes
Looks good, overall @dlcole3. Have some minor comments

2022-07-06 19:54 UTC, sshin23 commented on src/DynamicNLPModels.jl
> +    F::M  = (similar(Q, 0, size(R, 1)) .= 0.0),
zero(T)

2022-07-06 19:54 UTC, sshin23 commented on src/DynamicNLPModels.jl
>  end
Maybe good to add a docstring of explaining what are these. Or we can even point to the reference

2022-07-06 19:54 UTC, sshin23 commented on src/DynamicNLPModels.jl
>  function DenseLQDynamicBlocks(
is this constructor even necessary? can't we just use the default constructor?

2022-07-06 19:54 UTC, sshin23 commented on src/DynamicNLPModels.jl
> +    S::M  = (similar(Q, size(Q, 1), size(R, 1)) .= 0.0),
zero(T)

2022-07-06 19:54 UTC, sshin23 commented on src/DynamicNLPModels.jl
> +    G  = similar(Q, nc * N, nu); fill!(G, 0.0)
`zero(T)`

2022-07-06 19:54 UTC, sshin23 commented on src/DynamicNLPModels.jl
> +    J1 = similar(Q, nc * N, nu * N); fill!(J1, 0.0)
ok, this is the guy we want to eliminate later

2022-07-06 19:54 UTC, sshin23 commented on src/DynamicNLPModels.jl
> +    nnzh = floor(Int, size(H, 1) * (size(H,1) + 1) / 2)
`div( ... , 2)`

2022-07-06 21:07 UTC, frapac requested changes
I think this PR is still a work in progress, but most requests are easy to address. 

As a rule of thumb, I would advise
1. Use the broadcast operator consistently and ensure we are not allocating any new array inside a for loop
2. Move all the allocations (`similar`) at the beginning of the functions, so we can quickly assess how much memory is allocated
3. Use the notations from Kerrigan's paper consistently

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +    S::M  = (similar(Q, size(Q, 1), size(R, 1)) .= 0.0),
This syntax is too heavy and hard to parse. Prefer: 
```julia
S = similar(Q, n, m) ; fill!(S, 0,0)
```

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +    nnzh = floor(Int, size(H, 1) * (size(H,1) + 1) / 2)
For readability, prefer:
```julia
nh = size(H, 1)
nnzh = div(nh * (nh + 1), 2)
```

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +    G  = similar(Q, nc * N, nu); fill!(G, 0.0)
This is the dense Jacobian, right?

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +        dl[(1 + nc * (i - 1)): nc * i] = gl
use the broadcast operator here: `dl[...] .= gl`

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +            J2[(1 + (i - 1) * ns):end, (1 + nu * (i - 1)):(nu * i)] .= block_B[1:(ns * (N - i + 1)),:]
I would advise replacing `end` by the explicit indexing, to robustify the code

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +        dl[(1 + nc * (i - 1)): nc * i] = gl
or more directly: 
```julia
dl = repeat(gl, N)
```

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +    dense_blocks = _build_block_matrices(A, B, K, N)
hehe, just a remark: here `N` is an integer, but uses the same notation in capital as the other matrices

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +        dl[(1 + nc * (i - 1)): nc * i] = gl
Use the broadcast operator here, or `repeat`

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +        KAs0[(1 + nu * (i - 1)):nu * i] = KAs0_temp
broadcast operator

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +    for i in 1:nu
Or directly: `I_mat[diagind(I_mat)] .= 1.0`

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +            J3[(1 + (i + j - 2) * num_real_bounds):((i + j - 1) * num_real_bounds), (1 + nu * (i - 1)):(nu * i)] .= KBI[(1 + (j - 1) * nu):(j * nu), :][bool_vec_u, :]
indentation!

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
>          if i == 1
I don't like this syntax. I prefer to initialize the stage `i==1` before entering in the for loop, and then iterates with `for i in 2:(N-1)`

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +            block_A[(ns + 1):ns * 2, :] = A_k
Broadcast!

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +function _build_H_blocks(Q, R, block_A::M, block_B::M, S, s0, N, Qf, K::MK) where {T, M <: AbstractMatrix{T}, MK <: Nothing}
Be careful with the order of the arguments. To be consistent, it's better to put the matrices first, then the scalar arguments.

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +    QAB  = similar(block_A, ns, nu)
When we use `similar`, always initiate the resulting pointer with `0`!

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +        B_sub_block = block_B[(1 + (i - 1) * ns):(i * ns),:]
I guess this lead to unneeded allocations. Please consider using a view here

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +        QB[(1 + (i - 1) * ns):(i * ns), :]  = QAB
Broadcast!

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +                    view(H, row_range, col_range) .+= BQfB
genuine question: do we need a view here?

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +        QB_block_vec[(1 + ns * i):(ns * N), :] = QB[rows_QB, :]
broadcast!

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +function _build_H_blocks(Q, R, block_A::M, block_B::M, S::M, s0, N, Qf, K::MK) where {T, M <: AbstractMatrix, MK <: AbstractMatrix{T}}
genuine question: can we use a single `_build_H_blocks` function instead of two? Just to avoid code duplicate.

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +    RK_STB    = similar(block_B, nu, nu)
also: rule of thumb, for an old-school guy: always allocate the arrays at the beginning of the function (in C, your compiler should tell you to do so)

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +    RK_STB    = similar(block_B, nu, nu)
if we stick to that convention, it's a lot easier to assess how much memory is allocated inside one function

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +            G[(1 + nc * i):(nc * (i + 1)), :] = EB
broadcast!

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +    G[1:nc, :] = F
broadcast!

2022-07-06 21:07 UTC, frapac commented on src/DynamicNLPModels.jl
> +            B_sub_block = block_B[(1 + (i - 1) * ns):(i * ns),:]
please consider using a view here

2022-07-06 21:34 UTC, dlcole3 commented on src/DynamicNLPModels.jl
> +    G  = similar(Q, nc * N, nu); fill!(G, 0.0)
Not quite. The `G` matrix makes up part of the dense Jacobian. For the sake of memory, I actually just save the first block column of the `G` matrix, and then I fill the Jacobian separately. The Jacobian is also made up of the variable bounds (which become algebraic constraints). I have a couple prepared equations I will show tomorrow.

2022-07-06 21:35 UTC, dlcole3 commented on src/DynamicNLPModels.jl
> +        dl[(1 + nc * (i - 1)): nc * i] = gl
Woah, I wish I knew about the `repeat` function a long time ago :) I will be adding that in several places. Thank you!

2022-07-06 21:39 UTC, dlcole3 commented on src/DynamicNLPModels.jl
> +                    view(H, row_range, col_range) .+= BQfB
@frapac Yes, I believe so. I played with several things, but the `view` was the one that led to the smallest number of allocations. I honestly don't know why, but when I used other things (like `H[row_range, col_range]`), this was far less efficient and took lots more memory.

2022-07-07 13:47 UTC, dlcole3 commented on src/DynamicNLPModels.jl
> +function _build_H_blocks(Q, R, block_A::M, block_B::M, S::M, s0, N, Qf, K::MK) where {T, M <: AbstractMatrix, MK <: AbstractMatrix{T}}
I think we can. Previously, `_build_H_blocks` had to have more memory allocation within it to account for more multiplications. However, now the memory allocation difference is negligible under the new formulation. I checked the allocation for a large scale problem, and the two functions with and without `K` used 2.313 GiB vs. 2.311 GiB respectively.

2022-07-07 14:00 UTC, dlcole3 commented on src/DynamicNLPModels.jl
> +    S::M  = (similar(Q, size(Q, 1), size(R, 1)) .= 0.0),
@frapac can I do `fill!(S, 0)` within the function argument? This is setting the default value. I used `.= 0` because I wasn't sure how it would manage a `fill!` function within the function arguments.

2022-07-07 20:05 UTC, dlcole3 commented
I also updated the `build_thinplate.jl` file in the `examples/` folder. This used the old `DenseLQDynamicBlocks` structure

2022-07-07 21:01 UTC, dlcole3 commented
@frapac I made one more change after requesting reviews again (sorry, I should've added it before requesting reviews). I realized I am allocating extra memory for the Jacobian. I essentially was buliding the Jacobian twice. I removed the extra `J1`, `J2`, and `J3` matrices in the most recent commit.

2022-07-08 15:34 UTC, frapac approved these changes
Just an indentation issue, but otherwise it looks good to merge. 

Good work!

2022-07-08 15:34 UTC, frapac commented on src/DynamicNLPModels.jl
> +            J[(offset_u + 1 + (i + j - 2) * num_real_bounds_u):(offset_u + (i + j - 1) * num_real_bounds_u), (1 + nu * (i - 1)):(nu * i)] = @view(KBI[(1 + (j - 1) * nu):(j * nu), :][bool_vec_u, :])
indentation!

2022-07-08 15:59 UTC, merged